package question.easy;

import java.util.HashMap;
import java.util.Map;

/**
 * question.easy.
 *
 * @author Created by WXG on 2019-12-20 15:52
 * @version V1.0
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindtheDifference {

    public static void main(String[] args) {
        FindtheDifference findtheDifference = new FindtheDifference();
        String s = "dasdas";
        String t = "dasdars";
        System.out.println(findtheDifference.findTheDifference(s, t));
    }

    public char findTheDifference(String s, String t) {
        Map<Character, Character> map = new HashMap<>();
        char[] schars = s.toCharArray();
        char[] tchars = t.toCharArray();
        for (char schar : schars) {
            map.put(schar, schar);
        }

        char temp = tchars[0];
        for (char tchar : tchars) {
            Character character = map.get(tchar);
            if (character == null) {
                temp = tchar;
                break;
            }
        }

        return temp;
    }

    /**
     * 异或
     *
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference1(String s, String t) {
        String c = s + t;
        char[] chars = c.toCharArray();
        char res = 0;
        for (char aChar : chars) {
            res ^= aChar;
        }
        return res;
    }

    /**
     * 字符串替换
     *
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference2(String s, String t) {
        for (Character c : s.toCharArray()) {
            t = t.replaceFirst(c.toString(), "");
        }
        return t.toCharArray()[0];
    }

}
